-- CRISIS EN ELECTROINGENIERÍA · Multiequipo / Game Master
-- Diseñado para Supabase Postgres 17 + RLS. Ejecutar en un proyecto dedicado al juego.

create extension if not exists pgcrypto;

create table if not exists public.game_sessions (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  team_name text not null check (char_length(team_name) between 1 and 60),
  player_name text not null check (char_length(player_name) between 1 and 80),
  callsign text not null check (char_length(callsign) between 1 and 30),
  character_class text not null check (character_class in ('inspector','analyst','engineer')),
  accent text not null default '#ffd43b',
  score integer not null default 0,
  remaining_seconds integer not null default 2700,
  errors integer not null default 0,
  health integer not null default 100,
  stage text not null default 'briefing',
  objective text not null default '',
  status text not null default 'playing' check (status in ('playing','paused','completed','failed')),
  progress jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists game_sessions_owner_idx on public.game_sessions(owner_user_id);
create index if not exists game_sessions_status_idx on public.game_sessions(status, updated_at desc);

create table if not exists public.game_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.game_sessions(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists game_events_session_idx on public.game_events(session_id, created_at desc);

create table if not exists public.gm_commands (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.game_sessions(id) on delete cascade,
  command text not null check (command in ('pause','resume','add_time','remove_time','message','finish')),
  payload jsonb not null default '{}'::jsonb,
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists gm_commands_session_idx on public.gm_commands(session_id, created_at desc);

alter table public.game_sessions enable row level security;
alter table public.game_events enable row level security;
alter table public.gm_commands enable row level security;

-- Los jugadores usan Auth anónimo. Cada navegador-equipo solo puede leer/modificar su propia sesión.
drop policy if exists "players read own session" on public.game_sessions;
create policy "players read own session" on public.game_sessions for select to authenticated
using ((select auth.uid()) = owner_user_id or (select auth.jwt()->'app_metadata'->>'role') = 'game_master');

drop policy if exists "players create own session" on public.game_sessions;
create policy "players create own session" on public.game_sessions for insert to authenticated
with check ((select auth.uid()) = owner_user_id);

drop policy if exists "players update own session" on public.game_sessions;
create policy "players update own session" on public.game_sessions for update to authenticated
using ((select auth.uid()) = owner_user_id or (select auth.jwt()->'app_metadata'->>'role') = 'game_master')
with check ((select auth.uid()) = owner_user_id or (select auth.jwt()->'app_metadata'->>'role') = 'game_master');

-- Eventos: el jugador inserta los propios; Game Master puede observar todos.
drop policy if exists "players insert own events" on public.game_events;
create policy "players insert own events" on public.game_events for insert to authenticated
with check ((select auth.uid()) = owner_user_id and exists (
  select 1 from public.game_sessions s where s.id = session_id and s.owner_user_id = (select auth.uid())
));

drop policy if exists "game master reads events" on public.game_events;
create policy "game master reads events" on public.game_events for select to authenticated
using ((select auth.jwt()->'app_metadata'->>'role') = 'game_master');

-- Comandos: sólo Game Master crea. El dueño de la sesión puede recibir los comandos de su equipo.
drop policy if exists "game master creates commands" on public.gm_commands;
create policy "game master creates commands" on public.gm_commands for insert to authenticated
with check ((select auth.jwt()->'app_metadata'->>'role') = 'game_master' and (select auth.uid()) = created_by);

drop policy if exists "team receives commands" on public.gm_commands;
create policy "team receives commands" on public.gm_commands for select to authenticated
using (
  (select auth.jwt()->'app_metadata'->>'role') = 'game_master'
  or exists (select 1 from public.game_sessions s where s.id = session_id and s.owner_user_id = (select auth.uid()))
);

-- Data API: desde 2026 Supabase puede no exponer nuevas tablas automáticamente.
grant select, insert, update on public.game_sessions to authenticated;
grant select, insert on public.game_events to authenticated;
grant select, insert on public.gm_commands to authenticated;
grant usage, select on sequence public.game_events_id_seq to authenticated;
grant usage, select on sequence public.gm_commands_id_seq to authenticated;

-- Realtime para tablero y órdenes. Evita duplicar membresía de publicación.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'game_sessions') then
    alter publication supabase_realtime add table public.game_sessions;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'gm_commands') then
    alter publication supabase_realtime add table public.gm_commands;
  end if;
end $$;

comment on table public.game_sessions is 'Estado vivo de equipos en Crisis en Electroingeniería.';
comment on table public.game_events is 'Telemetría pedagógica y de gameplay por equipo.';
comment on table public.gm_commands is 'Órdenes autorizadas del Game Master hacia una sesión.';
